/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.4.2/userguide/multi_project_builds.html
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "snyk-sample"

include("app", "list", "utilities", "ui")


renameBuildFiles(rootProject)

fun renameBuildFiles(project: ProjectDescriptor) {
    project.buildFileName = if (File(
            project.projectDir,
            "${project.name}.gradle.kts"
        ).isFile
    ) "${project.name}.gradle.kts" else "${project.name}.gradle"
    project.children.forEach {
        renameBuildFiles(it)
    }
}