/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("snyk.sample.java-library-conventions")
}

dependencies {
    implementation("org.apache.logging.log4j:log4j-core:2.14.0")
    testImplementation("org.springframework:spring-webmvc:5.3.14")
}