/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("io.snyk.gradle.plugin.snykplugin")
    id("com.github.node-gradle.node")
}

snyk {
    setArguments("--file=${projectDir}/package.json --package-manager=npm")
    setSeverity("low")
}
